### PR TITLE
Fix for issue when --user flag for pip was added inside a virtual environment

### PR DESCRIPTION
**Pull request by duelle**
The addition of the `--user` flag to the node type of the AWS Platform lead to issues when the deployment was executed within a Python virtual environment (`virtualenv`) as described in #86.

This change implements a switch, depending on whether there is an enabled virtual environment or not. If there is a virtual environment active, the `--user` flag is not added to the calls, while it is applied in all other cases.

@AlexSpart Could you please check that this does not break anything on your side (which was supposed to be fixed by the addition of the `--user` flag)?

### CODE REVIEW

**Comment by miwurster** [comment]
LGTM ... If @AlexSpart gives his "Go", I will merge it.

**Review by miwurster — APPROVED** [review]

**Review by v-yussupov — APPROVED** [review]
LGTM

**Comment by miwurster** [comment]
@duelle could you please resolve the conflict?

**Review by AlexSpart — APPROVED** [review]
I have tested it and the the deployment succeeds with your modification @duelle.
Thanks for cross-check.

**Comment by duelle** [comment]
> @duelle could you please resolve the conflict?

Done @miwurster

**Pull request merged**
