### PR TITLE
Fix types concerning decomposition

### PR DESCRIPTION
**Pull request by miwurster**
Fixes based on discussions with @zhululai 

---

- [x] The `endpoint` requirement of `radon.nodes.aws.AwsLambdaFunction` are already inherited from `radon.nodes.abstract.Function`
- [x] The `invocable` capability of `radon.nodes.aws.AwsLambdaFunction` are already inherited from `radon.nodes.abstract.Function`
- [x] Name property of `radon.nodes.aws.AwsS3Bucket` is a duplicate as it is in the definition of `tosca.nodes.Abstract.Storage` already
- [x] Add name property to `radon.nodes.abstract.Workload` type
- [x] Update README.md of `radon.nodes.aws.AwsS3Bucket` and `radon.nodes.abstract.Workload`;
- [x] Rename `radon.relationships.abstract.ConnectsTo` to `radon.relationships.ConnectsTo`
- [x] Added badges to node type READMEs
- [x] `radon.relationships.abstract.Triggers` now derives from `tosca.relationships.ConnectsTo`

### CODE REVIEW

**Comment by miwurster** [comment]
Did not fix the `invocable` as this further restricts the `valid_source_types` to AWS types.

Also, did not fix the last point as I don't see a problem why the overwriting of `valid_source_types` is an issue here. @zhululai can elaborate on why this required?

**Comment by zhululai** [comment]
Thanks Micheal. I have reviewed the changes in this pull request.

My comments are as follows:
1. Do not remove the `host` requirement from `radon.nodes.aws.AwsLambdaFunction`;
2. Please update README.md of `radon.nodes.aws.AwsS3Bucket` and `radon.nodes.abstract.Workload`;
3. The service templates of some examples also need to be updated.

Regarding your question, a Lambda function can be invoked directly by a wide range of nodes, for example a user device (workload), an S3 bucket, another Lambda function, an EC2 instance or even a Google cloud function, so we'd better not restrict source types that are valid to the `invocable` capability of `radon.nodes.aws.AwsLambdaFunction`.

BTW, I am not sure why `radon.relationships.abstract.Triggers` should be derived from `tosca.relationships.DependsOn` instead of `tosca.relationships.Root`.

**Comment by miwurster** [comment]
Applied the requested changes, please review and approve.

Btw, `radon.relationships.abstract.Triggers` must derived from `tosca.relationships.DependsOn` such that xOpera can derive the correct execution order based on that. `DependsOn` is a normative type and inherently supported.

**Comment by miwurster** [comment]
@zhululai pls check again and approve.

Note, that I cannot just fix "some" service templates. This should be fixed by the person who works with it. Feel free to propose those changes in a follow-up PR.

**Review by v-yussupov — APPROVED** [review]
The changes look good to me

**Comment by miwurster** [comment]
@zhululai ping

**Comment by miwurster** [comment]
@zhululai pls check

**Comment by zhululai** [comment]
Sorry for the late review.

Everything looks great to me. Here are my additional comments regarding the Rename ''ConnectsTo" commit:
1. Please modify the `targetNamespace` of `radon.relationships.ConnectsTo` accordingly;
2. The README.md of `radon.relationships.abstract.Triggers` needs to be updated too.

In my mind, the type definitions are still under rapid evolution so we'd better leave the maintenance of examples to their owners.

**Pull request merged**
