### PR TITLE
Fix policy syntax in SockShopTestingExample

### PR DESCRIPTION
**Pull request by FlxB2**
Signed-off-by: Felix Burk <felix.burk@googlemail.com>

- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files

## Short Description

The proposed changes fix the policies of the SockShopTestingExample, because they were saved as a map instead of a list of maps.

## Resolving Issue / Feature

Related to [OpenTOSCA PR #216](https://github.com/OpenTOSCA/winery/pull/216) and to [radon-gmt issue #47](https://github.com/radon-h2020/radon-gmt/issues/47)

### CODE REVIEW

**Review by miwurster — APPROVED** [review]

**Comment by miwurster** [comment]
@duelle we had to change the serialization format of policies. Please review if these changes.

**Comment by miwurster** [comment]
@anzoman could you please confirm and comment if xOpera can work with policies serialized as a list?

According to the standard, policies need to be serialized as a list (example shown [here](https://github.com/radon-h2020/radon-gmt/issues/47#issue-714754937)).

**Comment by anzoman** [comment]
@miwurster xOpera currently expects to receive policies as a map (see this [example](https://github.com/xlab-si/xopera-opera/blob/master/examples/policy_triggers/service.yaml#L170)). I see that TOSCA states differently and that we need to accept a list and not a dict (map) here so I assume that this needs to be fixed ASAP (cc @cankarm).

**Comment by miwurster** [comment]
Yah I agree this must be fixed asap in xopera. 

GMT now ignores policies that are serialized as a map. So atm saving a service template containing policies as a map would remove those.

**Comment by anzoman** [comment]
This should be now fixed in opera (you can try it with opera dev version: https://test.pypi.org/project/opera/0.6.3.dev2/) and will be fully available within the next opera patch release.

**Review by miwurster — APPROVED** [review]

**Comment by miwurster** [comment]
@duelle if you are fine with merging this, please approve ;-)

**Comment by cankarm** [comment]
@duelle, can you try this? Thanks.

**Review by duelle — APPROVED** [review]

**Pull request merged**
