### PR TITLE
Fix the IAM role issue for Lambda functions

### PR DESCRIPTION
**Pull request by zhululai**
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files

---

## Short Description

This pull request aims to fix the IAM role issue for Lambda functions.

## Resolving Issue / Feature

An IAM role with `AWSLambdaFullAccess` is used to grant Lambda functions full access to AWS services. However, this policy is deprecated and replaced by `AWSLambda_FullAccess` (see [[1]](https://docs.aws.amazon.com/lambda/latest/dg/security_iam_troubleshoot.html#security_iam_troubleshoot-admin-deprecation)), which causes failure in deploying any RADON models with Lambda functions. To fix this issue, a list of nominally disjoint policies are combined to create the global IAM role. Supporting others AWS services accessible by Lambda functions would require extending the new IAM role with more policies.

### CODE REVIEW

**Review by miwurster — CHANGES_REQUESTED** [review]
This cannot be merged. You have to start with the new changes from the latest `master`. You have to supply a branch that only contains the fixes for the AWS IAM role.

**Comment by zhululai** [comment]
> This cannot be merged. You have to start with the new changes from the latest `master`. You have to supply a branch that only contains the fixes for the AWS IAM role.

I am not sure why the commits in my fork can't be synchronized. As a matter of fact, only the latest commit makes differences. Would you mind simply reviewing that commit? I will create a new fork next time to ensure only new commits are included.

**Comment by miwurster** [comment]
Well you always should use a clean branch for every new PR. Reusing an old could cause conflicts - like here. The PRs get merged with the option "squash and merge" which will squash all your commits into a single (new) commit. Therefore, the history of the upstream/master and your commit no longer match. If you gonna reuse such a branch, you will face the same issue like we have it here now.

The changes from the last commit look good though. However, I cannot merge the branch like this.

**Comment by miwurster** [comment]
To fix your branch you could try to "hard reset" to upstream/master, commit the fix and "force push" to your own remote.

Alternatively, "hard reset" your `master` to upstream/master, create a branch, apply your fix, and push. Then create a PR from there...

**Comment by zhululai** [comment]
> To fix your branch you could try to "hard reset" to upstream/master, commit the fix and "force push" to your own remote.
> 
> Alternatively, "hard reset" your `master` to upstream/master, create a branch, apply your fix, and push. Then create a PR from there...

Thanks a lot. SKILLS UPGRADED!

**Pull request closed without merging**
