### PR TITLE
Fixing minor issues with structure of node types and scheduling capabilities

### PR DESCRIPTION
**Pull request by chinmaya-dehury**
## Resolving Issue / Feature

- Updated the structure of [`Standalone`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline/Standalone) pipelines.
- Updated some data pipeline node types with missing scheduling feature.
- Fixed minor issues:
     - Modified [`AWSPlatform `](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.aws/AwsPlatform) nodetype to host data pipeline based node types.
     - Fixed minor issue in [`ConsGCSBucket`](https://github.com/radon-h2020/radon-particles/tree/master/nodetypes/radon.nodes.datapipeline.source/ConsGCSBucket)

### CODE REVIEW

**Comment by miwurster** [comment]
Is this PR ready to be reviewed?

**Comment by chinmaya-dehury** [comment]
> Is this PR ready to be reviewed?

Yes @miwurster , there were some conflicts before. All conflicts are resolved and is ready to be reviewed.

**Comment by miwurster** [comment]
Did you do a touch on the repository?

Chinmaya Dehury <notifications@github.com> schrieb am Mo., 8. März 2021,
15:18:

**Comment by chinmaya-dehury** [comment]
After touch on the repo, we did some minor modifications on very specific files (not through the Winery).

**Review by miwurster — APPROVED** [review]

**Comment by chinmaya-dehury** [comment]
Thanks @miwurster .

**Pull request merged**
