### PR TITLE
Refactor all nodes needed for the Monitoring tool to be deployed through SaaS. Event triggering included

### PR DESCRIPTION
**Pull request by sydkbc**
- [ ] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [ ] Ensure to use auto format in **all** files

---

### CODE REVIEW

**Comment by v-yussupov** [comment]
Thank you for the contribution, @sydkbc! Please, address the following issues:
1) Resolve the existing file conflicts
2) Apply WInery's auto-formatting feature, which will automatically normalize the introduced changes, e.g., import statements are not needed in the definitions - they are automatically generated during the CSAR export. Here's where you can find this feature:
image
3) Recheck that your modifications work and do not affect some of the existing Service Templates that rely on your modifications, e.g., SockShop or ServerlessToDoListAPI

**Review by v-yussupov — CHANGES_REQUESTED** [review]
The following issues need to be addressed before proceeding:
https://github.com/radon-h2020/radon-particles/pull/104#issuecomment-864192461

**Comment by sydkbc** [comment]
As far as the first 2 points are concerned I think it is feasible.

Regarding the last bullet (Recheck that your modifications work and do not affect some of the existing Service Templates that rely on your modifications, e.g., SockShop or ServerlessToDoListAPI):

As I mentioned before, the particles were updated so that the Monitoring tool can be deployed over xOpera SaaS along with all the event triggering functionality. As far as I saw other examples that were deployed over SaaS as well, I am not confident that this will not cause any issues to other service templates. 

If I am not mistaken the basis of the particles is designed for usage through xOpera CLI mainly.

**Comment by v-yussupov** [comment]
hi @sydkbc, I think since the majority of types are related to monitoring it is enough to just mention in the READMEs in case only the SaaS-based deployment is supported.
There are changes to general-purpose types, however (EC2 and LambdaFromS3), and these types are supposed to work for both CLI and SaaS-based deployments.
For the latter you can check if the following template can be deployed using CLI:
https://github.com/radon-h2020/radon-particles/tree/master/servicetemplates/radon.blueprints/ThumbnailGeneration_FromS3-w1-wip1

@duelle, could you suggest a deployable EC2-based service template?

**Comment by duelle** [comment]
One ST you could use for testing EC2 deployment would be the `JMeterMasterOnlyEC2` service template: https://github.com/radon-h2020/radon-particles/tree/master/servicetemplates/radon.blueprints.testing/JMeterMasterOnlyEC2

**Comment by duelle** [comment]
In the Ansible playbook for EC2 I was wondering whether other changes might be necessary on the users end if there are different categories of hosts like `vms`: https://github.com/radon-h2020/radon-particles/blob/ba755803ef35d87452969db379cd04fbcc037026/nodetypes/radon.nodes.VM/EC2/files/create/create.yml#L39

**Comment by sydkbc** [comment]
> In the Ansible playbook for EC2 I was wondering whether other changes might be necessary on the users end if there are different categories of hosts like `vms`:
> 
> https://github.com/radon-h2020/radon-particles/blob/ba755803ef35d87452969db379cd04fbcc037026/nodetypes/radon.nodes.VM/EC2/files/create/create.yml#L39



> In the Ansible playbook for EC2 I was wondering whether other changes might be necessary on the users end if there are different categories of hosts like `vms`:
> 
> https://github.com/radon-h2020/radon-particles/blob/ba755803ef35d87452969db379cd04fbcc037026/nodetypes/radon.nodes.VM/EC2/files/create/create.yml#L39

Actually, this modification was performed because currently(in the particles) the EC2 node cannot be deployed over SaaS.
Same issue emerged of course when someone wants to ssh to the VM and deploy docker or an application.

My reference for this was this:
https://github.com/xlab-si/xopera-examples/tree/master/cloud/aws/thumbnail-generator-with-vm

**Comment by v-yussupov** [comment]
closing this as it was decided to create a new PR when the merge issues are resolved

**Pull request closed without merging**
