### PR TITLE
Fourth integration of type definitions for the decomposition tool

### PR DESCRIPTION
**Pull request by zhululai**
- [x] Ensure that the commit message is [a good commit message](https://github.com/joelparkerhenderson/git_commit_message)
- [x] Ensure to use auto format in **all** files

---

## Short Description

This pull request includes the type definitions needed to create the toolchain demonstrator (serverless todo list API) that can be optimized by the decomposition tool.

## Resolving Issue / Feature

In particular, the following new features have been enabled by the pull request:
1. QoS modeling of API gateways, databases and DBMSs
2. Support of flexible entries for workloads and functions

A few errors were also fixed when the upstream was merged into the fork.

### CODE REVIEW

**Review by v-yussupov — COMMENTED** [review]
the changes look good to me! @zhululai have you checked if the modified Service Templates are still deployable?

**Comment by zhululai** [comment]
> the changes look good to me! @zhululai have you checked if the modified Service Templates are still deployable?

**Comment by zhululai** [comment]
> the changes look good to me! @zhululai have you checked if the modified Service Templates are still deployable?

I have deployed the ServerlessToDoListAPI example with xOpera. During the deployment, an additional issue is found regarding the global IAM role for Lambda functions. It is not introduced by this pull request and requires modification of Ansible playbooks. Therefore, I would like to come up with another pull request to fix it after this one is accepted and merged into the upsteam repository.

**Comment by zhululai** [comment]
> the changes look good to me! @zhululai have you checked if the modified Service Templates are still deployable?

I don't have an account to test the Google Cloud examples, but I am sure that they should work as the modification is minor.

**Review by miwurster — APPROVED** [review]

**Pull request merged**
